#!/bin/sh

while read file
do
    case "$1" in
        "y")
            echo "$PWD/$file" | tr -d "\n" | xclip -selection c
            notify-send "$PWD/$file"
            ;;
        "Y")
            echo $PWD/$file | tr -d "\n" | xclip -selection c
            notify-send "$PWD/$file"
            ;;
        "w")
            # feh --bg-fill "$file"
            swww-daemon & disown; swww img "$file"
            cp "$file" ~/.cache/wallpaper
            ;;
        "r")
            mv "$file" `echo $file | rofi -dmenu -i "$file"`
            ;;
        "y")
            echo "$file" | xclip -selection c
            ;;
        "d")
            rm "$file"
            notify-send "deleted $file"
            ;;
    esac
done