#!/usr/bin/env sh

# get volume
get_volume() {
	status=`amixer get Master | tail -n1 | grep -wo 'on'`

	if [[ "$status" == "on" ]]; then
		volume=`amixer get Master | tail -n1 | awk -F ' ' '{print $5}' | tr -d '[]'`
		echo "$volume"
	else
		echo "Mute"
	fi
}

# get icons
get_icon() {
	vol="$(get_volume)"
	current="${vol%%%}"
	status=`amixer get Master | tail -n1 | grep -wo 'on'`

	if [[ "$status" == "on" ]]; then
		if [[ "$current" -eq "0" ]]; then
			echo "images/icons/audio/mute.png"
		elif [[ ("$current" -ge "0") && ("$current" -le "30") ]]; then
			echo "images/icons/audio/volume.png"
		elif [[ ("$current" -ge "30") && ("$current" -le "60") ]]; then
			echo "images/icons/audio/volume.png"
		elif [[ ("$current" -ge "60") && ("$current" -le "100") ]]; then
			echo "images/icons/audio/volume.png"
		fi
	else
		echo "images/icons/audio/mute.png"
	fi
}

# increase volume
inc_volume() {
	amixer -Mq set Master,0 5%+ unmute
}

# decrease volume
dec_volume() {
	amixer -Mq set Master,0 5%- unmute
}

# toggle mute
toggle_mute() {
	status=`amixer get Master | tail -n1 | grep -wo 'on'`

	if [[ "$status" == "on" ]]; then
		amixer set Master toggle
	else
		amixer set Master toggle
	fi
}

# execute accordingly
if [[ "$1" == "--get" ]]; then
	get_volume
elif [[ "$1" == "--icon" ]]; then
	get_icon
elif [[ "$1" == "--inc" ]]; then
	inc_volume
elif [[ "$1" == "--dec" ]]; then
	dec_volume
elif [[ "$1" == "--toggle" ]]; then
	toggle_mute
else
	get_volume
fi